server:
  port: 30030
spring:
  banner:
    location: classpath:banner.txt
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://45.84.210.174:65432/cd2025bfp1g4
    username: testuser
    password: testuser
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.SQLServerDialect
logging:
  level:
    org:
      hibernate:
        SQL: debug
      type:
        descriptor:
          sql: trace
jwt:
  secret: xlJQSlmC4lT8HPtBY6vCf07klWfhUMmQze
  expiration: 36000000